language: php

dist: bionic

git:
  quiet: true

cache:
  directories:
    - $HOME/.composer
    - vendor

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

matrix:
  fast_finish: true

install:
  - composer update --no-interaction --no-progress --prefer-dist --optimize-autoloader $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
